title: "XU, Sihong"
author: "XU Sihong"
description: "2023 © XU Sihong
<a href="https://hits.seeyoufarm.com"><img src="https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fsxubi.github.io&count_bg=%236F6F6F&title_bg=%230F4D92&icon=atom.svg&icon_color=%23E7E7E7&title=Viewers&edge_flat=false"/></a>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header


# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: Home}
  - {file: "education.md", title: Education}
  - {file: "research.md", title: Research}
  - {file: "protectpre.md", title: Posts}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "xu_sihong@berkeley.edu"}
  - {title: Github, icon: github, url: "https://github.com/sxubi"}
  - {title: Bilibili, icon: calculator, url: "https://www.wolframalpha.com/"}
  - {title: Physics, icon: atom, url: "https://physics.ust.hk"}

plugins:
 - jekyll-feed
