title: "XU Sihong"
author: "XU Sihong"
description: "HKUST, Clear Water Bay, Kowloon"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
mathjax: true 

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: Home}
  - {file: "cv.pdf", title: Education}
  - {file: "cv.pdf", title: Research}
  - {file: "archive.html", title: Posts}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: P, icon: "fa-sharp fa-solid fa-square-p" , url: }
  - {title: H, icon: "fa-sharp fa-solid fa-square-h"  , url: }
  - {title: Y, icon: "fa-sharp fa-solid fa-square-y"  , url: }
  - {title: S, icon: "fa-sharp fa-solid fa-square-s"  , url: }
  - {title: I, icon: "fa-sharp fa-solid fa-square-i"  , url: }
  - {title: C, icon: "fa-sharp fa-solid fa-square-c"  , url: }
  - {title: S, icon: "fa-sharp fa-solid fa-square-s"  , url: }


plugins:
 - jekyll-feed
