title: "Sihong Xu"
author: "Sihong Xu"
description: "2024 © Sihong Xu"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header


# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: Home}
  - {file: "education.md", title: Education}
  - {file: "research.md", title: Research}
  #- {file: "pub.md", title: Publications}
  # - {file: "protectpre.md", title: Posts}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: , url:""}
  #- {title: Physics@HKUST, url: "https://physics.ust.hk"}
  #- {title: Group Website, url: "https://thequantumlab.org"}
  #- {title: overleaf, icon: leaf, url: "https://overleaf.com"}
  #- {title: Translate, icon: language, url: "https://translate.google.com"}
  #- {title: Wolframe, icon: calculator, url: "https://www.wolframalpha.com/"}
  #- {title: Physics, icon: atom, url: "https://stackexchange.com/"}

plugins:
 - jekyll-feed
