title: "XU, Sihong"
author: "XU Sihong"
description: "2023 © XU Sihong"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header


# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: Home}
  - {file: "education.md", title: Education}
  - {file: "research.md", title: Research}
  - {file: "archive.html", title: Posts}

external:
  - {title: Bilibili, icon: bilibili, url: "https://space.bilibili.com/88448358?spm_id_from=333.1007.0.0"}





plugins:
 - jekyll-feed
